version: "3.9"

services:
  db:
    image: docker.io/postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: aelp
      POSTGRES_PASSWORD: aelp
      POSTGRES_DB: aelp
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app:z
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend